### ISSUE TITLE
Segmentation fault in __kmp_fork_barrier

### ISSUE THREAD

**Issue by simoatze** [OpenMPToolsInterface/LLVM-openmp#14]
@jprotze I am gettin a seg fault [here](https://github.com/OpenMPToolsInterface/LLVM-openmp/blob/tr4-stable/runtime/src/kmp_barrier.cpp#L1776), only in a LLNL machine (i.e. Catalyst).

If I remember correctly we already had this problem, in the assignment `pId->ptr=NULL;`, `pId` has been already deallocated. Commenting that line doesn't show the problem.

**Comment by jprotze** [comment]
You are right. This should completely go away there.
