### ISSUE TITLE
ompt_callback_sync_region_wait event name

### ISSUE THREAD

**Issue by yanyh15** [OpenMPToolsInterface/LLVM-openmp#24]
https://github.com/OpenMPToolsInterface/LLVM-openmp/blob/towards_tr4/runtime/src/include/50/ompt.h.var#L120
```
    macro (ompt_callback_sync_region_wait,      ompt_callback_sync_region_t,   14) /* sync region wait begin or end*/  \
```

Is this typo or something that has not yet implemented and instead used ompt_callback_sync_region_t for ompt_callback_sync_region_wait_t?

Thanks
Yonghong

**Comment by jprotze** [comment]
No, this no error. This is exactly as specified in the spec. Both callbacks share the same type signature and arguments. For reference of further callbacks, that share the type signature see:
https://github.com/OpenMPToolsInterface/LLVM-openmp/blob/towards_tr4/runtime/test/ompt/callback.h#L670

**Comment by yanyh15** [comment]
Thank you. I was confused with the event type.
