### ISSUE TITLE
weak attribute on ompt_start_tool

### ISSUE THREAD

**Issue by jprotze** [OpenMPToolsInterface/LLVM-openmp#27]
For a static OpenMP runtime library, the weak attribute allows the function to co-exist with another implementation in the same object, i.e., the tool can be a static library as well, and both can be linked into the application without a linker issue.

Is the weak attribute necessary on ompt_start_tool for a dynamic library in [ompt-general.cpp#L105](https://github.com/OpenMPToolsInterface/LLVM-openmp/blob/towards_tr4/runtime/src/ompt-general.cpp#L105)?

From my understanding after reading [this discussion](https://software.intel.com/en-us/forums/intel-c-compiler/topic/386159), we can remove the weak flag for dynamic builds and therefore remove the restriction that the weak attribute needs to be available:

**Comment by hansangbae** [comment]
I think you are right.
By default, dynamic linker just stops searching for the symbol after a successful search, ignoring "weak" attribute according to [this thread](https://gcc.gnu.org/ml/gcc-help/2011-03/msg00224.html). The man page of "ld.so" also confirms that we need to define LD_DYNAMIC_WEAK to allow weak symbols to be overridden.

**Comment by jprotze** [comment]
I think we need the implementation of ompt_start_tool only to detect whether the linker has found an implementation before loading the runtime. If this fails, we already use dlsym to look for other implementations. With these two steps we should be able to detect any linked tool.

LD_DYNAMIC_WEAK could help to aviod the use of dlsym. But I think, this would lead to a lot of confusion and the dlsym solution is clearer for use.

On the other hand with dlsym-only we could not find ompt_start_tool in the binary unless compiled with `-rdynamic`. That's why the direct call with the fallback implementation is necessary as well.
