### ISSUE TITLE
Initialization for Windows

### ISSUE THREAD

**Issue by jprotze** [OpenMPToolsInterface/LLVM-openmp#3]
Tool initialization for Windows needs to be adapted

**Comment by jmellorcrummey** [comment]
Do you mean adapted? Or are you talking about the scanning of the libraries in the tool library path being similar to what windows must do?

--
John Mellor-Crummey

(sent from my phone)

**Comment by jprotze** [comment]
Yes, I meant adapted.
We updated the tool-initialization for Linux to the point, that it works as specified with the weak symbol approach. And we have the remaining work-flow on our list of work items.

But we will not touch the Windows part of tool initialization. Thus, I tracked this issue to be fixed by someone else
