### ISSUE TITLE
backtraces in ompt-specific.cpp?

### ISSUE THREAD

**Issue by jmellorcrummey** [OpenMPToolsInterface/LLVM-openmp#31]
@sconvent 

I am puzzled why ompt-specific.cpp includes support for collecting backtraces with libunwind. 

First, the provided routines don't seem to be used to support any routine in the OMPT API. 

Second, there doesn't seem to be anything that is runtime specific in this implementation. If the routines can be justified, why aren't they implemented in ompt-general.cpp.

**Comment by jprotze** [comment]
The use of this function is currently not active (https://github.com/OpenMPToolsInterface/LLVM-openmp/blob/towards_tr4/runtime/src/ompt-internal.h#L109).
Since we solved the issues that we had with the return-address with a different approach, we can remove this code (and also the includes).
