### ISSUE TITLE
codeptr_ra is nil for sync_region_begin/end and sync_region_wait_begin/end callback trigged by non-master threads

### ISSUE THREAD

**Issue by yanyh15** [OpenMPToolsInterface/LLVM-openmp#32]
the codeptr_ra for sync_region_begin and sync_region_wait_begin callbacks are passed as nil for non-master threads.  

For the test case:
````
 #pragma omp parallel  
   {   
        int id = omp_get_thread_num();
        printf("Hello, world %d.\n", id);
   }   
````
The grepped callback.h output is: 

````
yanyh@vm:~/tools/llvm-openmp/runtime/test/ompt$ make run | grep barrier
281474976710657: ompt_event_barrier_begin: parallel_id=281474976710660, task_id=281474976710661, codeptr_ra=0x4006c1
281474976710657: ompt_event_wait_barrier_begin: parallel_id=281474976710660, task_id=281474976710661, codeptr_ra=0x4006c1
562949953421313: ompt_event_barrier_begin: parallel_id=281474976710660, task_id=562949953421314, codeptr_ra=(nil)
562949953421313: ompt_event_wait_barrier_begin: parallel_id=281474976710660, task_id=562949953421314, codeptr_ra=(nil)
844424930131969: ompt_event_barrier_begin: parallel_id=281474976710660, task_id=844424930131970, codeptr_ra=(nil)
844424930131969: ompt_event_wait_barrier_begin: parallel_id=281474976710660, task_id=844424930131970, codeptr_ra=(nil)
1125899906842625: ompt_event_barrier_begin: parallel_id=281474976710660, task_id=1125899906842626, codeptr_ra=(nil)
1125899906842625: ompt_event_wait_barrier_begin: parallel_id=281474976710660, task_id=1125899906842626, codeptr_ra=(nil)
281474976710657: ompt_event_wait_barrier_end: parallel_id=281474976710660, task_id=281474976710661, codeptr_ra=0x4006c1
281474976710657: ompt_event_barrier_end: parallel_id=281474976710660, task_id=281474976710661, codeptr_ra=0x4006c1
1125899906842625: ompt_event_wait_barrier_end: parallel_id=0, task_id=1125899906842626, codeptr_ra=(nil)
844424930131969: ompt_event_wait_barrier_end: parallel_id=0, task_id=844424930131970, codeptr_ra=(nil)
844424930131969: ompt_event_barrier_end: parallel_id=0, task_id=844424930131970, codeptr_ra=(nil)
1125899906842625: ompt_event_barrier_end: parallel_id=0, task_id=1125899906842626, codeptr_ra=(nil)
562949953421313: ompt_event_wait_barrier_end: parallel_id=0, task_id=562949953421314, codeptr_ra=(nil)
562949953421313: ompt_event_barrier_end: parallel_id=0, task_id=562949953421314, codeptr_ra=(nil)

````

I have the following patch, which seems a fix:

````

diff --git a/runtime/src/kmp_barrier.cpp b/runtime/src/kmp_barrier.cpp
index 93c21dd..1acb1d7 100644
--- a/runtime/src/kmp_barrier.cpp
+++ b/runtime/src/kmp_barrier.cpp
@@ -1611,9 +1611,8 @@ void __kmp_join_barrier(int gtid) {
 #if OMPT_OPTIONAL
     void *codeptr = NULL;
     int ds_tid = this_thr->th.th_info.ds.ds_tid;
-    if (KMP_MASTER_TID(ds_tid) &&
-        (ompt_callbacks.ompt_callback(ompt_callback_sync_region_wait) ||
-        ompt_callbacks.ompt_callback(ompt_callback_sync_region)))
+    if (ompt_callbacks.ompt_callback(ompt_callback_sync_region_wait) ||
+        ompt_callbacks.ompt_callback(ompt_callback_sync_region))
         codeptr = team->t.ompt_team_info.master_return_address;
     my_task_data = OMPT_CUR_TASK_DATA(this_thr);
     my_parallel_data = OMPT_CUR_TEAM_DATA(this_thr);
diff --git a/runtime/src/kmp_runtime.cpp b/runtime/src/kmp_runtime.cpp
index 03dcf6a..5bd1935 100644
--- a/runtime/src/kmp_runtime.cpp
+++ b/runtime/src/kmp_runtime.cpp
@@ -7124,9 +7124,8 @@ void __kmp_internal_join(ident_t *id, int gtid, kmp_team_t *team) {
     this_thr->th.ompt_thread_info.state = omp_state_overhead;
 #if OMPT_OPTIONAL
     void * codeptr = NULL;
-    if (KMP_MASTER_TID(ds_tid) &&
-        (ompt_callbacks.ompt_callback(ompt_callback_sync_region_wait) ||
-        ompt_callbacks.ompt_callback(ompt_callback_sync_region)))
+    if (ompt_callbacks.ompt_callback(ompt_callback_sync_region_wait) ||
+        ompt_callbacks.ompt_callback(ompt_callback_sync_region))
         codeptr = this_thr->th.th_team->t.ompt_team_info.master_return_address;
 
     if (ompt_enabled.ompt_callback_sync_region_wait) {
@@ -7138,11 +7137,6 @@ void __kmp_internal_join(ident_t *id, int gtid, kmp_team_t *team) {
           ompt_sync_region_barrier, ompt_scope_end, pId, tId, codeptr);
     }   
 #endif
-    if (!KMP_MASTER_TID(ds_tid) &&
-        ompt_enabled.ompt_callback_implicit_task) {
-      ompt_callbacks.ompt_callback(ompt_callback_implicit_task)(
-          ompt_scope_end, NULL, tId, 0, ds_tid);
-    }
     // return to idle state
     this_thr->th.ompt_thread_info.state = omp_state_overhead;
   }   

````

The callback.h output:

````
yanyh@vm:~/tools/llvm-openmp/runtime/test/ompt$ make run  | grep barrier
281474976710657: ompt_event_barrier_begin: parallel_id=281474976710660, task_id=281474976710661, codeptr_ra=0x4006c1
281474976710657: ompt_event_wait_barrier_begin: parallel_id=281474976710660, task_id=281474976710661, codeptr_ra=0x4006c1
562949953421313: ompt_event_barrier_begin: parallel_id=281474976710660, task_id=562949953421314, codeptr_ra=0x4006c1
562949953421313: ompt_event_wait_barrier_begin: parallel_id=281474976710660, task_id=562949953421314, codeptr_ra=0x4006c1
844424930131969: ompt_event_barrier_begin: parallel_id=281474976710660, task_id=844424930131970, codeptr_ra=0x4006c1
844424930131969: ompt_event_wait_barrier_begin: parallel_id=281474976710660, task_id=844424930131970, codeptr_ra=0x4006c1
1125899906842625: ompt_event_barrier_begin: parallel_id=281474976710660, task_id=1125899906842626, codeptr_ra=0x4006c1
1125899906842625: ompt_event_wait_barrier_begin: parallel_id=281474976710660, task_id=1125899906842626, codeptr_ra=0x4006c1
281474976710657: ompt_event_wait_barrier_end: parallel_id=281474976710660, task_id=281474976710661, codeptr_ra=0x4006c1
281474976710657: ompt_event_barrier_end: parallel_id=281474976710660, task_id=281474976710661, codeptr_ra=0x4006c1
1125899906842625: ompt_event_wait_barrier_end: parallel_id=0, task_id=1125899906842626, codeptr_ra=(nil)
562949953421313: ompt_event_wait_barrier_end: parallel_id=0, task_id=562949953421314, codeptr_ra=(nil)
562949953421313: ompt_event_barrier_end: parallel_id=0, task_id=562949953421314, codeptr_ra=(nil)
844424930131969: ompt_event_wait_barrier_end: parallel_id=0, task_id=844424930131970, codeptr_ra=(nil)
844424930131969: ompt_event_barrier_end: parallel_id=0, task_id=844424930131970, codeptr_ra=(nil)
1125899906842625: ompt_event_barrier_end: parallel_id=0, task_id=1125899906842626, codeptr_ra=(nil)
````

sycn_region_end and sync_region_wait_end callbacks when invoked as part of the implicit-task-end event callback I believe, codeptr_ra is nil since the team data structure is not available at that point which is acceptable (I am referring to the __ompt_implicit_task_end function in kmp_wait_release.h). 

The current implementation use the return_address in the struct associate with the team object. 
What do you think to store the return address in the ompt_task_info of each thread so those per-thread info can still be retrieved when the team is destroyed. Each thread stores info in the ompt_task_info for later usage.

**Comment by jprotze** [comment]
The non-master threads are done with working on the parallel region at this point. There is no code these threads could return to. The patch you are suggesting provides invalid codeptr_ra, that cannot be found on the stack of the worker threads.

**Comment by jprotze** [comment]
For any barrier, that actually returns to code, you should see a meaningful codeptr.

**Comment by yanyh15** [comment]
For the meaning of the codeptr_ra, which I understand as the address tool uses to relate the callback to the source code, it is the address of the runtime routine, not the address the thread returns to. 

From the spec:

>The argument codeptr_ra is used to relate the implementation of an OpenMP region back to its source code. In cases where a runtime routine implements the region associated with this callback, codeptr_ra is expected to contain the return address of the call to the runtime routine

**Comment by jmellorcrummey** [comment]
Perhaps it is not clear enough, but the description you quoted says that "codeptr_ra is expected to contain the return address of the call to the runtime routine". That means an address in the user program where the runtime routine was explicitly called. If the runtime routine is **not** called from the user program but is called internally instead, e.g. an implicit barrier, one should expect a null codeptr_ra.

**Comment by jprotze** [comment]
@yanyh15 you only cited half of the spec description, the paragraph continues:
> ... In cases where the implementation of this feature is inlined, codeptr_ra is expected to contain the return address of the invocation of this callback. In cases where attribution to source code is impossible or inappropriate, codeptr_ra may be NULL.

In this case (implicit barrier at the end of the parallel region and implicit-task-end), my argument was that attribution is considered inappropriate. If you look at a backtrace, there is no application frame to return to.

**Comment by yanyh15** [comment]
I now do not disagree the nil return value for at the end of parallel region according to the spec. I am however not sure whether it is not inappropriate to have the address returned for non-master callbacks. it helps a tool to easily co-relate the region all the threads are in. That is why I need that address when searching a large number of trace records. So consider this as feature/implementation request, not an issue.

**Comment by jmellorcrummey** [comment]
you said: "... it helps a tool to easily co-relate the region all the threads are in. That is why I need that address when searching a large number of trace records"

I suggest that you use the "parallel_data" word associated with a parallel region to store an ID for the parallel region. The master can compute the ID and all the threads in the region can see and record it. That would easily let you identify the region a thread is in.

**Comment by jprotze** [comment]
If you need the parallel-id also for the barrier-end callback, you can copy the parallel-id into the task-blob at the implicit-task-begin. Then you can print/use the parallel-id to corelate also the barrier-end.

**Comment by yanyh15** [comment]
@jprotze and @jmellorcrummey thank you for your suggestions. That is mostly what I am doing, by storing the needed info in the global parallel_data->ptr (or id) so all the threads/implicit tasks can see it. I forgot to mention the other reason for that. The tool we are developing needs to have some online analysis feature so by the time a barrier_sync_region related callbacks are triggered (before implicit_task_end), it wants to know whether this reaches a join-barrier or it is for other kinds of implicit or explicit barrier (e.g. for a worksharing loop or an explicit barrier). The sync_region_begin marks the completion of the implicit task computation, not by the implicit-task-end event iteslf. That is why the sync_region_begin callback of the join barrier is important. My tool currently compares the codeptr_ra of the callback with the codeptr_ra of parallel_begin to determine whether the callbacks are for join barrier or not, though this relies on the compiler/runtime to let them point to the same address, which is true so far for llvm openmp. I now will let the tool to compare the passing codeptra_ra in the callback with nil to determine whether this is a join barrier or not, assuming this is the only situation that nil is returned for sycn_region_begin related callback. 

I basically needs a way to differentiate the callbacks for join-barrier from other types of barriers.
