### ISSUE TITLE
OMPT-placeholders

### ISSUE THREAD

**Issue by jprotze** [OpenMPToolsInterface/LLVM-openmp#33]
@jmellorcrummey in https://github.com/OpenMPToolsInterface/LLVM-openmp/blob/towards_tr4/runtime/src/ompt-general.cpp#L582 there are some placeholder functions defined. We cannot find anything about them in the spec.
Do you have strong feelings to have these functions there?

**Comment by hahnjo** [comment]
These functions have been removed in the upstream repository.
