### ISSUE TITLE
Return address for omp_init_lock

### ISSUE THREAD

**Issue by sconvent** [OpenMPToolsInterface/LLVM-openmp#36]
The changes in https://github.com/OpenMPToolsInterface/LLVM-openmp/commit/31483d0467188324d6f22aee7478226e0f7ae72a seem to be not compatible with intel compiler. The binary calls __kmpc_init_lock directly without going through omp_init_lock.
Is this code generated by the compiler, or inlined from the library? The value of the 4th argument  codeptr_ra seems to be the same as for the 3rd argument.

**Comment by hansangbae** [comment]
Intel compiler generates direct calls to __kmpc_* entry functions if it is compiling for Intel architecture for some of the OpenMP runtime routines, so I think the return address needs to be computed within __kmpc_* entries in such cases.

**Comment by jmellorcrummey** [comment]
I agree with @sconvent and @hansangbae. The kmpc_* routines should not have codeptr_ra as an argument. Instead, they should determine the codeptr_ra themselves internally by calling __builtin__return_address().

**Comment by jprotze** [comment]
Currently a call to omp_init_lock/__kmpc_init_lock does not initialize the runtime. This means, that a tool would not get an event for the initialization of the lock. Should the call trigger runtime initialization, so that a tool has the chance to get loaded?

**Comment by jmellorcrummey** [comment]
I don't think that we shouldn't trigger runtime initialization for a lock. I think the language committee would agree with my point of view.

**Comment by hansangbae** [comment]
The runtime is actually initialized by calling __kmp_entry_gtid if omp_init_lock is called, and Intel compiler inserts a call to __kmpc_global_thread_num instead for direct calls to __kmpc_init_lock, which eventually calls __kmp_entry_gtid.

**Comment by jprotze** [comment]
Fixed by 9131ddbf5620342501ffa707aadb2ec77d486f77
