### ISSUE TITLE
Current source won't build towards_tr4

### ISSUE THREAD

**Issue by khuck** [OpenMPToolsInterface/LLVM-openmp#37]
Getting this compilation error on OS X with Clang 5.0.0:

mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=../install -DLIBOMP_OMPT_SUPPORT=ON ..
make 

[  8%] Building CXX object runtime/src/CMakeFiles/omp.dir/ompt-general.cpp.o
In file included from /Users/khuck/src/LLVM-openmp/runtime/src/ompt-general.cpp:20:
/Users/khuck/src/LLVM-openmp/runtime/src/ompt-specific.cpp:212:6: error: use of undeclared identifier
      '__kmp_gtid'
  if(__kmp_gtid >= 0)
     ^
1 error generated.

This variable is defined in kmp.h, but deep in a nest of #ifdef pragmas...

**Comment by jprotze** [comment]
Kevin, thanks for catching this. We currently don't have a machine to test the runtime on OS X.

The idea of this if is to handle a call to ompt_get_thread_data() on a non-OpenMP thread without making the thread an OpenMP-thread. I think that 8cb3ae2 should fix the issue

**Comment by khuck** [comment]
No worries - I found the following patch will compile, not sure if it's correct though.

```
khuck@kevinmacbookair:~/src/LLVM-openmp$ git diff runtime/src/ompt-specific.cpp 
diff --git a/runtime/src/ompt-specific.cpp b/runtime/src/ompt-specific.cpp
index dfd7968..367c501 100644
--- a/runtime/src/ompt-specific.cpp
+++ b/runtime/src/ompt-specific.cpp
@@ -209,7 +209,7 @@ __ompt_get_scheduling_taskinfo(int depth)
 //----------------------------------------------------------
 
 ompt_data_t *__ompt_get_thread_data_internal() {
-  if(__kmp_gtid >= 0)
+  if(__kmp_gtid_get_specific() >= 0)
   {
     kmp_info_t *thread = ompt_get_thread();
     if(thread==NULL) return NULL;
```
