### ISSUE TITLE
bug in returning thread_num of ompt_get_task_info ?

### ISSUE THREAD

**Issue by yanyh15** [OpenMPToolsInterface/LLVM-openmp#43]
Just realized that i need to post issue here (sent email to openmp-dev)

https://github.com/llvm-mirror/openmp/blob/master/runtime/src/ompt-specific.cpp#L400

From the spec: 
444:16-17Version 5.0 rev 2, November 2017

16 If a non-NULL value was passed for thread_num, the value returned in *thread_num indicates the

17  number of the thread in the parallel region executing the task.

It should return thread_num of the thread in the team, not the gtid?

**Comment by jmellorcrummey** [comment]
I believe that this was fixed in a patch proposed by Joachim Protze, but perhaps the pull request has not been accepted yet. 
--
John Mellor-Crummey		Professor
Dept of Computer Science	Rice University
email: johnmc@rice.edu		phone: 713-348-5179

**Comment by yanyh15** [comment]
Thank you John. close it now.

**Comment by jprotze** [comment]
@sconvent we should thoroughly test this for nested parallelism.
I pushed an improved implementation in branch fix-nested-thread-num

@yanyh15 does this fix your issue?

**Comment by yanyh15** [comment]
@jprotze yes. it works now. I did not test the nested parallelism.
