### ISSUE TITLE
Sections vs. static-for loops

### ISSUE THREAD

**Issue by jprotze** [OpenMPToolsInterface/LLVM-openmp#6]
Sections and static for loops use the same entrypoint.
Ompt makes a difference between sections and loops. 

See 4.6.2.18, 4.4.6.14

**Comment by omalyshe** [comment]
Filed the [ Bugzilla ](https://bugs.llvm.org/show_bug.cgi?id=33922) to add flags for static loop/sections/distribute.

**Comment by jprotze** [comment]
The flags are in the compiler: http://llvm.org/viewvc/llvm-project?rev=310865&view=rev

@omalyshe are the flags already evaluated in the runtime?

**Comment by omalyshe** [comment]
I will work on the runtime changes
