### ISSUE TITLE
dyn-var, stacksize-var, cancel-var, max-task-priority-var, debug-var support in ompd_enumerate_icvs() and ompd_get_icv_from_scope().

### ISSUE THREAD

**Issue by jinisusan** [OpenMPToolsInterface/LLVM-openmp#70]
While using ompd_enumerate_icvs() (from the ompd-tests branch) to get the list of ICVs, I realized that not all the ICVs are available through OMPD (Only around 6 (not counting the OMPD specific ICVs) are available from the list of about 22 ICVs).  

Including a patch here (off the ompd-tests branch) to include support for the following additional ICVs in ompd_enumerate_icvs() and ompd_get_icv_from_scope():
dyn-var, stacksize-var, cancel-var, max-task-priority-var, debug-var

I have targeted the ICVs (which have been more straightforward to retrieve) first. Planning to add support for the remaining ICVs piece-by-piece. 

[ompd-icv1-diff.txt](https://github.com/OpenMPToolsInterface/LLVM-openmp/files/3834845/ompd-icv1-diff.txt)

Could someone take a look at this patch and advise on how to proceed ? 

Thanks in advance!

**Comment by jprotze** [comment]
To review the code I find it easier to have a PR to the targeted branch. This allows to browse the surrounding code. If possible, just create a PR from your private fork.

**Comment by jprotze** [comment]
I accepted this patch as PR #71

**Comment by jinisusan** [comment]
Thanks a bunch, Joachim. Will create a PR the next time.
